version: "3.8"
services:
  postgres_timezone:
    image: ibrahim966/ecommerce-database:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: 'fashion_db'
      POSTGRES_USER: 'fashion_user'
      POSTGRES_PASSWORD: 'fashion_user123'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    container_name: ecommerce_container
    ports:
      - 8000:8000
    image: ibrahim966/ecommerce-server:latest
    command: gunicorn --bind 0.0.0.0:8000 ecommerce.wsgi:application
    depends_on:
      - postgres_timezone
  
volumes:
  postgres_data:
 




